name: Auto Deploy to GitHub Pages

on:
  push:
    branches: [ "game" ]
  pull_request:
    branches: [ "game" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Time Zone
        run: sudo timedatectl set-timezone 'Asia/Taipei'

      - name: Add GitHub into ssh_known
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Node.js Setup
        uses: actions/setup-node@v2
        with:
          node-version: "18.12.1"
          cache: 'npm'

      - name: Node.js Package install
        run: npm i -g hexo-cli && npm i

      - name: Deploy
        id: deploy
        uses: sma11black/hexo-action@v1.0.3
        with:
          deploy_key: ${{ secrets.GAME_SEC }}
          user_name: MiohitoKiri5474
          user_email: lltzpp@gmail.com
          commit_msg: ${{ github.event.head_commit.message }}
